### ISSUE TITLE
Did not render doctype as expected

### ISSUE THREAD

**Issue by alphatr** [AlloyTeam/sodajs#11]
when I use in node, code like this:

```javascript
soda('<!DOCTYPE html><p>Hello world</p>');
```

expect output as the input, but output this:
```html
<!doctype><p>Hello world</p></!doctype>
```

node version: v8.1.3
soda version: 0.4.8
nodewindow version: 1.0.9

**Comment by cjd6568358** [comment]
这是因为soda把html片段插入到DOM里，DOM解析引发的问题。遇到这事，自己可以再replace一遍就行了 ，如果是做node服务端渲染，可以参考 koa模版引擎 插件 koa-view-ng
