### ISSUE TITLE
怎么设置元素属性 如：input 的 checked

### ISSUE THREAD

**Issue by drmflying** [AlloyTeam/sodajs#18]

**Comment by dorsywang** [comment]
`
var tpl = `
<input soda-checked={{checked}} type="radio" />
<input soda-checked={{unchecked}} type="radio" />
<input soda-checked={{unclared}} type="radio" />
`;

document.getElementById('container').innerHTML =  soda(tpl, { checked: true, unchecked: undefined });
`

soda-*={{value}}   value为undefined时候不设置属性，其他情况全部设置属性
请帮忙分享下sodajs，感谢

**Comment by godtail** [comment]
感觉使用undefined不是特别好吧，针对那些需要判断的情况如下，会导致属性设置为false，然后还是会选中。

```javascript
var tpl = `
<ul>
    <select>
			<option soda-selected={{selected=='test1'}}>测试1<option>
			<option soda-selected={{selected=='test2'}}>测试2<option>
			<option soda-selected={{selected=='test3'}}>测试3<option>
		</select>
</ul>`

var data = {
    selected: 'test2'
};

document.getElementById('container').innerHTML =  soda(tpl, data);
```

例如上面这种情况就会导致全部选中了，感觉false的情况也需要处理，或者说仅仅针对属性是checked，selected时，false不设置属性，毕竟有的情况下，还是需要设置false的，考虑添加一个配置常量过滤下吧。

**Comment by drmflying** [comment]
var tpl = `
<input soda-checked={{checked}} type="checkbox"  value="0"/>

<input soda-checked={{checked}} type="checkbox" value="1"/>

<input soda-checked={{checked}} type="checkbox" value="2"/>
`;
var data = {
    checked: '0,1'
};
这种情况又该如何做呢？
soda-checked={{checked.indexOf('0')>=0?true:undefined}} 这种方式不支持啊
写了个filter返回的好像是字符串？

**Comment by godtail** [comment]
> .会解析成对象的属性，不能这样调用indexOf

我给一个比较奇葩的解决思路，使用filter，但是遗憾的是最后返回undefined的时候，并没有触发移除属性逻辑。

```javascri[t
var tpl = `
<input soda-checked={{checked|in:0|prop}} type="checkbox">
<input soda-checked={{checked|in:1|prop}} type="checkbox">
<input soda-checked={{checked|in:2|prop}} type="checkbox">
`

var data = {
    checked: '0,1'
};

soda.filter('in', function(items, key) {
  return items.indexOf(key) !== -1; 
});

soda.filter('prop', function(val) {
	return val === false ? undefined : val; // 这里会设置到属性为undefined，没触发移除属性的逻辑
})

document.getElementById('container').innerHTML =  soda(tpl, data);
```

**Comment by dorsywang** [comment]
按@godtail 的建议增加了对false的处理，如果为false就不添加属性
@drmflying 目前表达式暂不支持indexOf这种操作，推荐用filter
godtail的例子可以正确运行，也可以使用下面的例子
```
var tpl = `
<input soda-checked={{checked|in:0}} type="checkbox">
<input soda-checked={{checked|in:1}} type="checkbox">
<input soda-checked={{checked|in:2}} type="checkbox">
`

var data = {
    checked: '0,1'
};

soda.filter('in', function(items, key) {
  return items.indexOf(key) > -1; 
});



document.getElementById('container').innerHTML =  soda(tpl, data);
```

记得用最新的版本

**Comment by godtail** [comment]
> 其实上面的indexOf是有问题的，当时忘了补充了

数据如果是'0,11'，这种形式，indexOf('1')，获取不到预期的结果

1. 可以使用split分割成数组，再使用数组的indexOf来获取
2. 数据可以设置成',0,11,'（开头和结尾添加','字符），再使用',1,'来进行indexOf操作
