### ISSUE TITLE
能否支持koa2?

### ISSUE THREAD

**Issue by cjd6568358** [AlloyTeam/sodajs#4]
现在是只能在浏览器端使用，能否出一个koa2的插件

**Comment by dorsywang** [comment]
可以的，我们最近出一个node版本的sodajs

**Comment by cjd6568358** [comment]
最好可以做一个横向性能评测，看看性能和ejs相差多少

**Comment by cjd6568358** [comment]
@dorsywang 发现一个很严重的问题，你们这个模版引擎貌似不支持嵌套include？还有，刚看到你们有更新了，看了一下只是在node端可以跑起来，要想在koa2中使用它来渲染页面还远远不行吧？

**Comment by dorsywang** [comment]
@cjd6568358 为什么不能使用它在koa2来渲染页面呢？是因为担心性能问题？

**Comment by cjd6568358** [comment]
@dorsywang 首先是应该不支持include 模版嵌套吧？然后目前我用的中间件是koa-views,里面并没有对应的模版引擎支持，如果要使用的话就要自己实现这样一个中间件了

**Comment by cjd6568358** [comment]
@dorsywang 找到了一个类似的angular模版引擎，支持include。可惜只能用在Node端，你看看是否可以整合下？https://github.com/allenhwkim/angular-template

**Comment by dorsywang** [comment]
@cjd6568358 可以的，include我们来支持下

**Comment by cjd6568358** [comment]
@dorsywang 要是能支持cache就更好了，类似于pre-compile，angular-template 是支持的

**Comment by dorsywang** [comment]
感谢@cjd6568358同学的建议，这个会在下版本支持上

**Comment by cjd6568358** [comment]
@dorsywang 能否透露下啥时候新版本发布？就等着你们的模版引擎重写呢。。。哈哈

**Comment by cjd6568358** [comment]
@dorsywang 试了一下node端渲染，发现repeat指令有问题，会重复编译。
