### ISSUE TITLE
希望能开一个dev分支出来，方便添加一些特性

### ISSUE THREAD

**Issue by godtail** [AlloyTeam/sodajs#8]
1. pull requests都是直接合并到master分支的，如果别人更新可能导致兼容性问题。
2. 目前压缩后的soda.min.js在浏览器端报错（部分';'没加导致）

**Comment by dorsywang** [comment]
加了npm和cdn的版本的链接，git还做为开发分支，后续合并主干都会经过自动化测试再合入保证功能可用
