### ISSUE TITLE
如果模板为'<tr>...</tr>'类型时，会丢失tr、td等标签

### ISSUE THREAD

**Issue by godtail** [AlloyTeam/sodajs#9]
```javascript
var div = document.createElement("div");

        // 必须加入到body中去，不然自定义标签不生效
        if (document.documentMode < 9) {
            div.style.display = 'none';
            document.body.appendChild(div);
        }

        div.innerHTML = str;
```
这段代码把模板设置到div的innerHTML的时候，因为此时的tr、td为无效标签会丢失。

目前想到的两种解决方案：
1. 设置完整的table模板，再提取（操作复杂）。
2. 在tbody设置soda-repeat（每添加一个元素，重新渲染感觉效率低）。

不知道有没有比较好的解决此问题的方法？

> 注：我目前是重构中的多页old项目，如果是新的单页框架例如omi的话，没这个问题。

**Comment by dorsywang** [comment]
目前soda.js版本使用innerHTML渲染没有太好的办法，建议使用完整的html片段做模板;
如果对于兼容性要求不高，可以尝试使用soda.node.js版本，这个版本因为可以在node端使用，自带dom解析引擎，测试结果可以参照下面的两个链接
[soda.js版本测试](http://alloyteam.github.io/sodajs/test/soda-mocha.html)

[soda.node.js浏览器测试](http://alloyteam.github.io/sodajs/test/soda.node-mocha.html)

两个版本的区别可以参考这里
[区别](https://github.com/AlloyTeam/sodajs#usage)
